(cl:in-package tb_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CURRENT_X-VAL
          CURRENT_X
          CURRENT_Y-VAL
          CURRENT_Y
          CURRENT_YAW-VAL
          CURRENT_YAW
          GOAL_X-VAL
          GOAL_X
          GOAL_Y-VAL
          GOAL_Y
          GOAL_YAW-VAL
          GOAL_YAW
          YAW_GOALFRAME-VAL
          YAW_GOALFRAME
          DIRECT_GOALFRAME-VAL
          DIRECT_GOALFRAME
          E_D-VAL
          E_D
          E_DIR2GOAL-VAL
          E_DIR2GOAL
          E_YAW_POSEFRAME-VAL
          E_YAW_POSEFRAME
          DIR2GOAL_TERM-VAL
          DIR2GOAL_TERM
          YAW_TERM-VAL
          YAW_TERM
          LINEAR_VEL-VAL
          LINEAR_VEL
          ANGULAR_VEL-VAL
          ANGULAR_VEL
          DELTA_X_GOALFRAME-VAL
          DELTA_X_GOALFRAME
          DELTA_Y_GOALFRAME-VAL
          DELTA_Y_GOALFRAME
))