(cl:in-package tb_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCEL_LINEAR_XB-VAL
          ACCEL_LINEAR_XB
          ACCEL_LINEAR_YB-VAL
          ACCEL_LINEAR_YB
          ACCEL_LINEAR_ZB-VAL
          ACCEL_LINEAR_ZB
          ACCEL_AMPLITUDE-VAL
          ACCEL_AMPLITUDE
          VELO_LINEAR_XB_M_WHEELLEFT_GYROZ-VAL
          VELO_LINEAR_XB_M_WHEELLEFT_GYROZ
          VELO_LINEAR_XB_M_WHEELRIGHT_GYROZ-VAL
          VELO_LINEAR_XB_M_WHEELRIGHT_GYROZ
          VELO_LINEAR_XB_M_WHEEL-VAL
          VELO_LINEAR_XB_M_WHEEL
          VELO_ANGULAR_ZB_M_WHEEL-VAL
          VELO_ANGULAR_ZB_M_WHEEL
          WHEEL_LEFT_VELO_RAD-VAL
          WHEEL_LEFT_VELO_RAD
          WHEEL_RIGHT_VELO_RAD-VAL
          WHEEL_RIGHT_VELO_RAD
          VEL_XM-VAL
          VEL_XM
          VEL_YM-VAL
          VEL_YM
          VEL_ZM-VAL
          VEL_ZM
          POS_XM-VAL
          POS_XM
          POS_YM-VAL
          POS_YM
          POS_ZM-VAL
          POS_ZM
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
))