
(cl:in-package :asdf)

(defsystem "tb_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "GotoPoseAction" :depends-on ("_package_GotoPoseAction"))
    (:file "_package_GotoPoseAction" :depends-on ("_package"))
    (:file "GotoPoseActionFeedback" :depends-on ("_package_GotoPoseActionFeedback"))
    (:file "_package_GotoPoseActionFeedback" :depends-on ("_package"))
    (:file "GotoPoseActionGoal" :depends-on ("_package_GotoPoseActionGoal"))
    (:file "_package_GotoPoseActionGoal" :depends-on ("_package"))
    (:file "GotoPoseActionResult" :depends-on ("_package_GotoPoseActionResult"))
    (:file "_package_GotoPoseActionResult" :depends-on ("_package"))
    (:file "GotoPoseFeedback" :depends-on ("_package_GotoPoseFeedback"))
    (:file "_package_GotoPoseFeedback" :depends-on ("_package"))
    (:file "GotoPoseGoal" :depends-on ("_package_GotoPoseGoal"))
    (:file "_package_GotoPoseGoal" :depends-on ("_package"))
    (:file "GotoPoseResult" :depends-on ("_package_GotoPoseResult"))
    (:file "_package_GotoPoseResult" :depends-on ("_package"))
    (:file "autodock_status" :depends-on ("_package_autodock_status"))
    (:file "_package_autodock_status" :depends-on ("_package"))
    (:file "cmd_motor_pid_speed_setpoint" :depends-on ("_package_cmd_motor_pid_speed_setpoint"))
    (:file "_package_cmd_motor_pid_speed_setpoint" :depends-on ("_package"))
    (:file "cmd_motor_pwm" :depends-on ("_package_cmd_motor_pwm"))
    (:file "_package_cmd_motor_pwm" :depends-on ("_package"))
    (:file "cmd_servo_pos" :depends-on ("_package_cmd_servo_pos"))
    (:file "_package_cmd_servo_pos" :depends-on ("_package"))
    (:file "pid_debug" :depends-on ("_package_pid_debug"))
    (:file "_package_pid_debug" :depends-on ("_package"))
    (:file "pose_controller_debug" :depends-on ("_package_pose_controller_debug"))
    (:file "_package_pose_controller_debug" :depends-on ("_package"))
    (:file "robot_state" :depends-on ("_package_robot_state"))
    (:file "_package_robot_state" :depends-on ("_package"))
    (:file "servo_position" :depends-on ("_package_servo_position"))
    (:file "_package_servo_position" :depends-on ("_package"))
    (:file "tbcore_status" :depends-on ("_package_tbcore_status"))
    (:file "_package_tbcore_status" :depends-on ("_package"))
    (:file "wheel_encoder" :depends-on ("_package_wheel_encoder"))
    (:file "_package_wheel_encoder" :depends-on ("_package"))
  ))