# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robocup_msgs/OrganizedActionList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robocup_msgs.msg

class OrganizedActionList(genpy.Message):
  _md5sum = "c4e400b7194e474d9f55055a87400c2a"
  _type = "robocup_msgs/OrganizedActionList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """OAction[] actionList
================================================================================
MSG: robocup_msgs/OAction
gm_bus_msg action
int32 seq
================================================================================
MSG: robocup_msgs/gm_bus_msg
string action
string action_id
string payload
int64 result"""
  __slots__ = ['actionList']
  _slot_types = ['robocup_msgs/OAction[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       actionList

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OrganizedActionList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.actionList is None:
        self.actionList = []
    else:
      self.actionList = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.actionList)
      buff.write(_struct_I.pack(length))
      for val1 in self.actionList:
        _v1 = val1.action
        _x = _v1.action
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v1.action_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v1.payload
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v1.result
        buff.write(_get_struct_q().pack(_x))
        _x = val1.seq
        buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.actionList is None:
        self.actionList = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actionList = []
      for i in range(0, length):
        val1 = robocup_msgs.msg.OAction()
        _v2 = val1.action
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v2.action = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v2.action = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v2.action_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v2.action_id = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v2.payload = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v2.payload = str[start:end]
        start = end
        end += 8
        (_v2.result,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (val1.seq,) = _get_struct_i().unpack(str[start:end])
        self.actionList.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.actionList)
      buff.write(_struct_I.pack(length))
      for val1 in self.actionList:
        _v3 = val1.action
        _x = _v3.action
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v3.action_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v3.payload
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v3.result
        buff.write(_get_struct_q().pack(_x))
        _x = val1.seq
        buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.actionList is None:
        self.actionList = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actionList = []
      for i in range(0, length):
        val1 = robocup_msgs.msg.OAction()
        _v4 = val1.action
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v4.action = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v4.action = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v4.action_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v4.action_id = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v4.payload = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v4.payload = str[start:end]
        start = end
        end += 8
        (_v4.result,) = _get_struct_q().unpack(str[start:end])
        start = end
        end += 4
        (val1.seq,) = _get_struct_i().unpack(str[start:end])
        self.actionList.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
