// Generated by gencpp from file robocup_msgs/Entity2D.msg
// DO NOT EDIT!


#ifndef ROBOCUP_MSGS_MESSAGE_ENTITY2D_H
#define ROBOCUP_MSGS_MESSAGE_ENTITY2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>
#include <robocup_msgs/Box.h>

namespace robocup_msgs
{
template <class ContainerAllocator>
struct Entity2D_
{
  typedef Entity2D_<ContainerAllocator> Type;

  Entity2D_()
    : header()
    , pose()
    , label()
    , bounding_box()
    , score(0.0)  {
    }
  Entity2D_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , label(_alloc)
    , bounding_box(_alloc)
    , score(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef  ::robocup_msgs::Box_<ContainerAllocator>  _bounding_box_type;
  _bounding_box_type bounding_box;

   typedef float _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::robocup_msgs::Entity2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robocup_msgs::Entity2D_<ContainerAllocator> const> ConstPtr;

}; // struct Entity2D_

typedef ::robocup_msgs::Entity2D_<std::allocator<void> > Entity2D;

typedef boost::shared_ptr< ::robocup_msgs::Entity2D > Entity2DPtr;
typedef boost::shared_ptr< ::robocup_msgs::Entity2D const> Entity2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robocup_msgs::Entity2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robocup_msgs::Entity2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robocup_msgs::Entity2D_<ContainerAllocator1> & lhs, const ::robocup_msgs::Entity2D_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.label == rhs.label &&
    lhs.bounding_box == rhs.bounding_box &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robocup_msgs::Entity2D_<ContainerAllocator1> & lhs, const ::robocup_msgs::Entity2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robocup_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robocup_msgs::Entity2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocup_msgs::Entity2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_msgs::Entity2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_msgs::Entity2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_msgs::Entity2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_msgs::Entity2D_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robocup_msgs::Entity2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7162617965dabc489df7fa0955c3df7";
  }

  static const char* value(const ::robocup_msgs::Entity2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7162617965dabc4ULL;
  static const uint64_t static_value2 = 0x89df7fa0955c3df7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robocup_msgs::Entity2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocup_msgs/Entity2D";
  }

  static const char* value(const ::robocup_msgs::Entity2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robocup_msgs::Entity2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Pose2D pose\n"
"string label\n"
"Box bounding_box\n"
"float32 score\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: robocup_msgs/Box\n"
"int32 x\n"
"int32 y\n"
"int32 width\n"
"int32 height\n"
;
  }

  static const char* value(const ::robocup_msgs::Entity2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robocup_msgs::Entity2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.label);
      stream.next(m.bounding_box);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Entity2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robocup_msgs::Entity2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robocup_msgs::Entity2D_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "bounding_box: ";
    s << std::endl;
    Printer< ::robocup_msgs::Box_<ContainerAllocator> >::stream(s, indent + "  ", v.bounding_box);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCUP_MSGS_MESSAGE_ENTITY2D_H
