// Generated by gencpp from file robocup_msgs/Entity.msg
// DO NOT EDIT!


#ifndef ROBOCUP_MSGS_MESSAGE_ENTITY_H
#define ROBOCUP_MSGS_MESSAGE_ENTITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace robocup_msgs
{
template <class ContainerAllocator>
struct Entity_
{
  typedef Entity_<ContainerAllocator> Type;

  Entity_()
    : header()
    , pose()
    , uuid()
    , label()
    , type()
    , diameter(0.0)
    , payload()  {
    }
  Entity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , uuid(_alloc)
    , label(_alloc)
    , type(_alloc)
    , diameter(0.0)
    , payload(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _uuid_type;
  _uuid_type uuid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef float _diameter_type;
  _diameter_type diameter;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _payload_type;
  _payload_type payload;





  typedef boost::shared_ptr< ::robocup_msgs::Entity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robocup_msgs::Entity_<ContainerAllocator> const> ConstPtr;

}; // struct Entity_

typedef ::robocup_msgs::Entity_<std::allocator<void> > Entity;

typedef boost::shared_ptr< ::robocup_msgs::Entity > EntityPtr;
typedef boost::shared_ptr< ::robocup_msgs::Entity const> EntityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robocup_msgs::Entity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robocup_msgs::Entity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robocup_msgs::Entity_<ContainerAllocator1> & lhs, const ::robocup_msgs::Entity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.uuid == rhs.uuid &&
    lhs.label == rhs.label &&
    lhs.type == rhs.type &&
    lhs.diameter == rhs.diameter &&
    lhs.payload == rhs.payload;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robocup_msgs::Entity_<ContainerAllocator1> & lhs, const ::robocup_msgs::Entity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robocup_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robocup_msgs::Entity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocup_msgs::Entity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_msgs::Entity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_msgs::Entity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_msgs::Entity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_msgs::Entity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robocup_msgs::Entity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602e1507bca7794045dcb939ed5c2edf";
  }

  static const char* value(const ::robocup_msgs::Entity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602e1507bca77940ULL;
  static const uint64_t static_value2 = 0x45dcb939ed5c2edfULL;
};

template<class ContainerAllocator>
struct DataType< ::robocup_msgs::Entity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocup_msgs/Entity";
  }

  static const char* value(const ::robocup_msgs::Entity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robocup_msgs::Entity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Pose pose\n"
"string uuid\n"
"# Label of the current entity\n"
"string label\n"
"# Type of entity, king of object, people,...\n"
"string type\n"
"# Ground object occupation\n"
"float32 diameter\n"
"# Additional information regarding to the type of object\n"
"string payload\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robocup_msgs::Entity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robocup_msgs::Entity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.uuid);
      stream.next(m.label);
      stream.next(m.type);
      stream.next(m.diameter);
      stream.next(m.payload);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Entity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robocup_msgs::Entity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robocup_msgs::Entity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uuid);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "diameter: ";
    Printer<float>::stream(s, indent + "  ", v.diameter);
    s << indent << "payload: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.payload);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCUP_MSGS_MESSAGE_ENTITY_H
