// Generated by gencpp from file robocup_msgs/OrganizedActionList.msg
// DO NOT EDIT!


#ifndef ROBOCUP_MSGS_MESSAGE_ORGANIZEDACTIONLIST_H
#define ROBOCUP_MSGS_MESSAGE_ORGANIZEDACTIONLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robocup_msgs/OAction.h>

namespace robocup_msgs
{
template <class ContainerAllocator>
struct OrganizedActionList_
{
  typedef OrganizedActionList_<ContainerAllocator> Type;

  OrganizedActionList_()
    : actionList()  {
    }
  OrganizedActionList_(const ContainerAllocator& _alloc)
    : actionList(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robocup_msgs::OAction_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robocup_msgs::OAction_<ContainerAllocator> >::other >  _actionList_type;
  _actionList_type actionList;





  typedef boost::shared_ptr< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> const> ConstPtr;

}; // struct OrganizedActionList_

typedef ::robocup_msgs::OrganizedActionList_<std::allocator<void> > OrganizedActionList;

typedef boost::shared_ptr< ::robocup_msgs::OrganizedActionList > OrganizedActionListPtr;
typedef boost::shared_ptr< ::robocup_msgs::OrganizedActionList const> OrganizedActionListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robocup_msgs::OrganizedActionList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robocup_msgs::OrganizedActionList_<ContainerAllocator1> & lhs, const ::robocup_msgs::OrganizedActionList_<ContainerAllocator2> & rhs)
{
  return lhs.actionList == rhs.actionList;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robocup_msgs::OrganizedActionList_<ContainerAllocator1> & lhs, const ::robocup_msgs::OrganizedActionList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robocup_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4e400b7194e474d9f55055a87400c2a";
  }

  static const char* value(const ::robocup_msgs::OrganizedActionList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4e400b7194e474dULL;
  static const uint64_t static_value2 = 0x9f55055a87400c2aULL;
};

template<class ContainerAllocator>
struct DataType< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocup_msgs/OrganizedActionList";
  }

  static const char* value(const ::robocup_msgs::OrganizedActionList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "OAction[] actionList\n"
"================================================================================\n"
"MSG: robocup_msgs/OAction\n"
"gm_bus_msg action\n"
"int32 seq\n"
"================================================================================\n"
"MSG: robocup_msgs/gm_bus_msg\n"
"string action\n"
"string action_id\n"
"string payload\n"
"int64 result\n"
;
  }

  static const char* value(const ::robocup_msgs::OrganizedActionList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actionList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrganizedActionList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robocup_msgs::OrganizedActionList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robocup_msgs::OrganizedActionList_<ContainerAllocator>& v)
  {
    s << indent << "actionList[]" << std::endl;
    for (size_t i = 0; i < v.actionList.size(); ++i)
    {
      s << indent << "  actionList[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robocup_msgs::OAction_<ContainerAllocator> >::stream(s, indent + "    ", v.actionList[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCUP_MSGS_MESSAGE_ORGANIZEDACTIONLIST_H
