(cl:in-package tb_msgs-srv)
(cl:export '(PID_ID-VAL
          PID_ID
          ENABLE_SET_P-VAL
          ENABLE_SET_P
          ENABLE_SET_I-VAL
          ENABLE_SET_I
          ENABLE_SET_D-VAL
          ENABLE_SET_D
          ENABLE_SET_SETPOINT-VAL
          ENABLE_SET_SETPOINT
          P_VALUE-VAL
          P_VALUE
          I_VALUE-VAL
          I_VALUE
          D_VALUE-VAL
          D_VALUE
          SETPOINT-VAL
          SETPOINT
          PID_ID-VAL
          PID_ID
          P_VALUE-VAL
          P_VALUE
          I_VALUE-VAL
          I_VALUE
          D_VALUE-VAL
          D_VALUE
          SETPOINT-VAL
          SETPOINT
))