(cl:in-package tb_msgs-srv)
(cl:export '(STREAM_ENABLE-VAL
          STREAM_ENABLE
          ENABLE_SET_TBCORE-VAL
          ENABLE_SET_TBCORE
          TBCORE-VAL
          TBCORE
          ENABLE_SET_SERVO_NECK-VAL
          ENABLE_SET_SERVO_NECK
          SERVO_NECK-VAL
          SERVO_NECK
          ENABLE_SET_WHEEL_ENCODER-VAL
          ENABLE_SET_WHEEL_ENCODER
          WHEEL_ENCODER-VAL
          WHEEL_ENCODER
          ENABLE_SET_SERVO_EXT1-VAL
          ENABLE_SET_SERVO_EXT1
          SERVO_EXT1-VAL
          SERVO_EXT1
          ENABLE_SET_SERVO_EXT2-VAL
          ENABLE_SET_SERVO_EXT2
          SERVO_EXT2-VAL
          SERVO_EXT2
          STREAM_ENABLE-VAL
          STREAM_ENABLE
          TBCORE-VAL
          TBCORE
          SERVO_NECK-VAL
          SERVO_NECK
          WHEEL_ENCODER-VAL
          WHEEL_ENCODER
          SERVO_EXT1-VAL
          SERVO_EXT1
          SERVO_EXT2-VAL
          SERVO_EXT2
))