(cl:in-package tb_msgs-srv)
(cl:export '(ENABLE_CONTROLLER-VAL
          ENABLE_CONTROLLER
          PID_VELOCITY_MOTOR_LEFT-VAL
          PID_VELOCITY_MOTOR_LEFT
          PID_VELOCITY_MOTOR_RIGHT-VAL
          PID_VELOCITY_MOTOR_RIGHT
          ENABLE_CONTROLLER-VAL
          ENABLE_CONTROLLER
          PID_VELOCITY_MOTOR_LEFT-VAL
          PID_VELOCITY_MOTOR_LEFT
          PID_VELOCITY_MOTOR_RIGHT-VAL
          PID_VELOCITY_MOTOR_RIGHT
))