// Generated by gencpp from file tb_msgs/srv_cancel_all_goal.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_CANCEL_ALL_GOAL_H
#define TB_MSGS_MESSAGE_SRV_CANCEL_ALL_GOAL_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_cancel_all_goalRequest.h>
#include <tb_msgs/srv_cancel_all_goalResponse.h>


namespace tb_msgs
{

struct srv_cancel_all_goal
{

typedef srv_cancel_all_goalRequest Request;
typedef srv_cancel_all_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_cancel_all_goal
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_cancel_all_goal > {
  static const char* value()
  {
    return "456bd278eb75535185f071a7439ca165";
  }

  static const char* value(const ::tb_msgs::srv_cancel_all_goal&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_cancel_all_goal > {
  static const char* value()
  {
    return "tb_msgs/srv_cancel_all_goal";
  }

  static const char* value(const ::tb_msgs::srv_cancel_all_goal&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_cancel_all_goalRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_cancel_all_goal >
template<>
struct MD5Sum< ::tb_msgs::srv_cancel_all_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_cancel_all_goal >::value();
  }
  static const char* value(const ::tb_msgs::srv_cancel_all_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_cancel_all_goalRequest> should match
// service_traits::DataType< ::tb_msgs::srv_cancel_all_goal >
template<>
struct DataType< ::tb_msgs::srv_cancel_all_goalRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_cancel_all_goal >::value();
  }
  static const char* value(const ::tb_msgs::srv_cancel_all_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_cancel_all_goalResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_cancel_all_goal >
template<>
struct MD5Sum< ::tb_msgs::srv_cancel_all_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_cancel_all_goal >::value();
  }
  static const char* value(const ::tb_msgs::srv_cancel_all_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_cancel_all_goalResponse> should match
// service_traits::DataType< ::tb_msgs::srv_cancel_all_goal >
template<>
struct DataType< ::tb_msgs::srv_cancel_all_goalResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_cancel_all_goal >::value();
  }
  static const char* value(const ::tb_msgs::srv_cancel_all_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_CANCEL_ALL_GOAL_H
