// Generated by gencpp from file tb_msgs/srv_set_pid.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_SET_PID_H
#define TB_MSGS_MESSAGE_SRV_SET_PID_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_set_pidRequest.h>
#include <tb_msgs/srv_set_pidResponse.h>


namespace tb_msgs
{

struct srv_set_pid
{

typedef srv_set_pidRequest Request;
typedef srv_set_pidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_set_pid
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_set_pid > {
  static const char* value()
  {
    return "d810ba0aa21a126034f571f0e11e19fc";
  }

  static const char* value(const ::tb_msgs::srv_set_pid&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_set_pid > {
  static const char* value()
  {
    return "tb_msgs/srv_set_pid";
  }

  static const char* value(const ::tb_msgs::srv_set_pid&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_set_pidRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_set_pid >
template<>
struct MD5Sum< ::tb_msgs::srv_set_pidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_set_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_set_pidRequest> should match
// service_traits::DataType< ::tb_msgs::srv_set_pid >
template<>
struct DataType< ::tb_msgs::srv_set_pidRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_set_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_set_pidResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_set_pid >
template<>
struct MD5Sum< ::tb_msgs::srv_set_pidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_set_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_set_pidResponse> should match
// service_traits::DataType< ::tb_msgs::srv_set_pid >
template<>
struct DataType< ::tb_msgs::srv_set_pidResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_set_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_SET_PID_H
