// Generated by gencpp from file tb_msgs/srv_reset_wheel_odometry.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_RESET_WHEEL_ODOMETRY_H
#define TB_MSGS_MESSAGE_SRV_RESET_WHEEL_ODOMETRY_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_reset_wheel_odometryRequest.h>
#include <tb_msgs/srv_reset_wheel_odometryResponse.h>


namespace tb_msgs
{

struct srv_reset_wheel_odometry
{

typedef srv_reset_wheel_odometryRequest Request;
typedef srv_reset_wheel_odometryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_reset_wheel_odometry
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_reset_wheel_odometry > {
  static const char* value()
  {
    return "d317ea579fecd8ec18fe3db1a99405a3";
  }

  static const char* value(const ::tb_msgs::srv_reset_wheel_odometry&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_reset_wheel_odometry > {
  static const char* value()
  {
    return "tb_msgs/srv_reset_wheel_odometry";
  }

  static const char* value(const ::tb_msgs::srv_reset_wheel_odometry&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_reset_wheel_odometryRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_reset_wheel_odometry >
template<>
struct MD5Sum< ::tb_msgs::srv_reset_wheel_odometryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_reset_wheel_odometry >::value();
  }
  static const char* value(const ::tb_msgs::srv_reset_wheel_odometryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_reset_wheel_odometryRequest> should match
// service_traits::DataType< ::tb_msgs::srv_reset_wheel_odometry >
template<>
struct DataType< ::tb_msgs::srv_reset_wheel_odometryRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_reset_wheel_odometry >::value();
  }
  static const char* value(const ::tb_msgs::srv_reset_wheel_odometryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_reset_wheel_odometryResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_reset_wheel_odometry >
template<>
struct MD5Sum< ::tb_msgs::srv_reset_wheel_odometryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_reset_wheel_odometry >::value();
  }
  static const char* value(const ::tb_msgs::srv_reset_wheel_odometryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_reset_wheel_odometryResponse> should match
// service_traits::DataType< ::tb_msgs::srv_reset_wheel_odometry >
template<>
struct DataType< ::tb_msgs::srv_reset_wheel_odometryResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_reset_wheel_odometry >::value();
  }
  static const char* value(const ::tb_msgs::srv_reset_wheel_odometryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_RESET_WHEEL_ODOMETRY_H
