// Generated by gencpp from file tb_msgs/srv_debug_pid_streamRequest.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_DEBUG_PID_STREAMREQUEST_H
#define TB_MSGS_MESSAGE_SRV_DEBUG_PID_STREAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb_msgs
{
template <class ContainerAllocator>
struct srv_debug_pid_streamRequest_
{
  typedef srv_debug_pid_streamRequest_<ContainerAllocator> Type;

  srv_debug_pid_streamRequest_()
    : stream_enable(false)
    , pid_id(0)  {
    }
  srv_debug_pid_streamRequest_(const ContainerAllocator& _alloc)
    : stream_enable(false)
    , pid_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _stream_enable_type;
  _stream_enable_type stream_enable;

   typedef int64_t _pid_id_type;
  _pid_id_type pid_id;





  typedef boost::shared_ptr< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srv_debug_pid_streamRequest_

typedef ::tb_msgs::srv_debug_pid_streamRequest_<std::allocator<void> > srv_debug_pid_streamRequest;

typedef boost::shared_ptr< ::tb_msgs::srv_debug_pid_streamRequest > srv_debug_pid_streamRequestPtr;
typedef boost::shared_ptr< ::tb_msgs::srv_debug_pid_streamRequest const> srv_debug_pid_streamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator2> & rhs)
{
  return lhs.stream_enable == rhs.stream_enable &&
    lhs.pid_id == rhs.pid_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "413fd35685729a6ff6c381dabeb188fa";
  }

  static const char* value(const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x413fd35685729a6fULL;
  static const uint64_t static_value2 = 0xf6c381dabeb188faULL;
};

template<class ContainerAllocator>
struct DataType< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb_msgs/srv_debug_pid_streamRequest";
  }

  static const char* value(const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stream_enable\n"
"int64 pid_id\n"
;
  }

  static const char* value(const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stream_enable);
      stream.next(m.pid_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_debug_pid_streamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb_msgs::srv_debug_pid_streamRequest_<ContainerAllocator>& v)
  {
    s << indent << "stream_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stream_enable);
    s << indent << "pid_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pid_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_DEBUG_PID_STREAMREQUEST_H
