// Generated by gencpp from file tb_msgs/srv_get_pid.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_GET_PID_H
#define TB_MSGS_MESSAGE_SRV_GET_PID_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_get_pidRequest.h>
#include <tb_msgs/srv_get_pidResponse.h>


namespace tb_msgs
{

struct srv_get_pid
{

typedef srv_get_pidRequest Request;
typedef srv_get_pidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_get_pid
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_get_pid > {
  static const char* value()
  {
    return "80fc92f077ac3ba48f25169b714592b8";
  }

  static const char* value(const ::tb_msgs::srv_get_pid&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_get_pid > {
  static const char* value()
  {
    return "tb_msgs/srv_get_pid";
  }

  static const char* value(const ::tb_msgs::srv_get_pid&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_get_pidRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_get_pid >
template<>
struct MD5Sum< ::tb_msgs::srv_get_pidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_get_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_pidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_get_pidRequest> should match
// service_traits::DataType< ::tb_msgs::srv_get_pid >
template<>
struct DataType< ::tb_msgs::srv_get_pidRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_get_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_pidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_get_pidResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_get_pid >
template<>
struct MD5Sum< ::tb_msgs::srv_get_pidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_get_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_pidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_get_pidResponse> should match
// service_traits::DataType< ::tb_msgs::srv_get_pid >
template<>
struct DataType< ::tb_msgs::srv_get_pidResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_get_pid >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_pidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_GET_PID_H
