// Generated by gencpp from file tb_msgs/srv_set_pose_controller.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_SET_POSE_CONTROLLER_H
#define TB_MSGS_MESSAGE_SRV_SET_POSE_CONTROLLER_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_set_pose_controllerRequest.h>
#include <tb_msgs/srv_set_pose_controllerResponse.h>


namespace tb_msgs
{

struct srv_set_pose_controller
{

typedef srv_set_pose_controllerRequest Request;
typedef srv_set_pose_controllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_set_pose_controller
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_set_pose_controller > {
  static const char* value()
  {
    return "a7ecf8b74de4bfe7d43b400f40a2efe5";
  }

  static const char* value(const ::tb_msgs::srv_set_pose_controller&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_set_pose_controller > {
  static const char* value()
  {
    return "tb_msgs/srv_set_pose_controller";
  }

  static const char* value(const ::tb_msgs::srv_set_pose_controller&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_set_pose_controllerRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_set_pose_controller >
template<>
struct MD5Sum< ::tb_msgs::srv_set_pose_controllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_set_pose_controller >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pose_controllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_set_pose_controllerRequest> should match
// service_traits::DataType< ::tb_msgs::srv_set_pose_controller >
template<>
struct DataType< ::tb_msgs::srv_set_pose_controllerRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_set_pose_controller >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pose_controllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_set_pose_controllerResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_set_pose_controller >
template<>
struct MD5Sum< ::tb_msgs::srv_set_pose_controllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_set_pose_controller >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pose_controllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_set_pose_controllerResponse> should match
// service_traits::DataType< ::tb_msgs::srv_set_pose_controller >
template<>
struct DataType< ::tb_msgs::srv_set_pose_controllerResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_set_pose_controller >::value();
  }
  static const char* value(const ::tb_msgs::srv_set_pose_controllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_SET_POSE_CONTROLLER_H
