// Generated by gencpp from file tb_msgs/srv_ardock_calib.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_ARDOCK_CALIB_H
#define TB_MSGS_MESSAGE_SRV_ARDOCK_CALIB_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_ardock_calibRequest.h>
#include <tb_msgs/srv_ardock_calibResponse.h>


namespace tb_msgs
{

struct srv_ardock_calib
{

typedef srv_ardock_calibRequest Request;
typedef srv_ardock_calibResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_ardock_calib
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_ardock_calib > {
  static const char* value()
  {
    return "b97a9f8d3d1c86973dd6c609bcce509a";
  }

  static const char* value(const ::tb_msgs::srv_ardock_calib&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_ardock_calib > {
  static const char* value()
  {
    return "tb_msgs/srv_ardock_calib";
  }

  static const char* value(const ::tb_msgs::srv_ardock_calib&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calibRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calib >
template<>
struct MD5Sum< ::tb_msgs::srv_ardock_calibRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_ardock_calib >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calibRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_ardock_calibRequest> should match
// service_traits::DataType< ::tb_msgs::srv_ardock_calib >
template<>
struct DataType< ::tb_msgs::srv_ardock_calibRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_ardock_calib >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calibRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calibResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calib >
template<>
struct MD5Sum< ::tb_msgs::srv_ardock_calibResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_ardock_calib >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calibResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_ardock_calibResponse> should match
// service_traits::DataType< ::tb_msgs::srv_ardock_calib >
template<>
struct DataType< ::tb_msgs::srv_ardock_calibResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_ardock_calib >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calibResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_ARDOCK_CALIB_H
