// Generated by gencpp from file tb_msgs/srv_ardock_calib_feedback.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_ARDOCK_CALIB_FEEDBACK_H
#define TB_MSGS_MESSAGE_SRV_ARDOCK_CALIB_FEEDBACK_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_ardock_calib_feedbackRequest.h>
#include <tb_msgs/srv_ardock_calib_feedbackResponse.h>


namespace tb_msgs
{

struct srv_ardock_calib_feedback
{

typedef srv_ardock_calib_feedbackRequest Request;
typedef srv_ardock_calib_feedbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_ardock_calib_feedback
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_ardock_calib_feedback > {
  static const char* value()
  {
    return "b970224db8c8334d7170f908c2834a66";
  }

  static const char* value(const ::tb_msgs::srv_ardock_calib_feedback&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_ardock_calib_feedback > {
  static const char* value()
  {
    return "tb_msgs/srv_ardock_calib_feedback";
  }

  static const char* value(const ::tb_msgs::srv_ardock_calib_feedback&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calib_feedbackRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calib_feedback >
template<>
struct MD5Sum< ::tb_msgs::srv_ardock_calib_feedbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_ardock_calib_feedback >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calib_feedbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_ardock_calib_feedbackRequest> should match
// service_traits::DataType< ::tb_msgs::srv_ardock_calib_feedback >
template<>
struct DataType< ::tb_msgs::srv_ardock_calib_feedbackRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_ardock_calib_feedback >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calib_feedbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calib_feedbackResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_ardock_calib_feedback >
template<>
struct MD5Sum< ::tb_msgs::srv_ardock_calib_feedbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_ardock_calib_feedback >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calib_feedbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_ardock_calib_feedbackResponse> should match
// service_traits::DataType< ::tb_msgs::srv_ardock_calib_feedback >
template<>
struct DataType< ::tb_msgs::srv_ardock_calib_feedbackResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_ardock_calib_feedback >::value();
  }
  static const char* value(const ::tb_msgs::srv_ardock_calib_feedbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_ARDOCK_CALIB_FEEDBACK_H
