// Generated by gencpp from file tb_msgs/srv_connect_portsRequest.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_CONNECT_PORTSREQUEST_H
#define TB_MSGS_MESSAGE_SRV_CONNECT_PORTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb_msgs
{
template <class ContainerAllocator>
struct srv_connect_portsRequest_
{
  typedef srv_connect_portsRequest_<ContainerAllocator> Type;

  srv_connect_portsRequest_()
    {
    }
  srv_connect_portsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srv_connect_portsRequest_

typedef ::tb_msgs::srv_connect_portsRequest_<std::allocator<void> > srv_connect_portsRequest;

typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsRequest > srv_connect_portsRequestPtr;
typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsRequest const> srv_connect_portsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb_msgs/srv_connect_portsRequest";
  }

  static const char* value(const ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_connect_portsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tb_msgs::srv_connect_portsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_CONNECT_PORTSREQUEST_H
