// Generated by gencpp from file tb_msgs/srv_connectResponse.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_CONNECTRESPONSE_H
#define TB_MSGS_MESSAGE_SRV_CONNECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb_msgs
{
template <class ContainerAllocator>
struct srv_connectResponse_
{
  typedef srv_connectResponse_<ContainerAllocator> Type;

  srv_connectResponse_()
    : is_connected(false)
    , port_name()  {
    }
  srv_connectResponse_(const ContainerAllocator& _alloc)
    : is_connected(false)
    , port_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_connected_type;
  _is_connected_type is_connected;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _port_name_type;
  _port_name_type port_name;





  typedef boost::shared_ptr< ::tb_msgs::srv_connectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb_msgs::srv_connectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_connectResponse_

typedef ::tb_msgs::srv_connectResponse_<std::allocator<void> > srv_connectResponse;

typedef boost::shared_ptr< ::tb_msgs::srv_connectResponse > srv_connectResponsePtr;
typedef boost::shared_ptr< ::tb_msgs::srv_connectResponse const> srv_connectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb_msgs::srv_connectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tb_msgs::srv_connectResponse_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_connectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_connected == rhs.is_connected &&
    lhs.port_name == rhs.port_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tb_msgs::srv_connectResponse_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_connectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_connectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_connectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_connectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdd7c1701ff28c1259311628bc31417b";
  }

  static const char* value(const ::tb_msgs::srv_connectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdd7c1701ff28c12ULL;
  static const uint64_t static_value2 = 0x59311628bc31417bULL;
};

template<class ContainerAllocator>
struct DataType< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb_msgs/srv_connectResponse";
  }

  static const char* value(const ::tb_msgs::srv_connectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_connected\n"
"string port_name\n"
"\n"
;
  }

  static const char* value(const ::tb_msgs::srv_connectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_connected);
      stream.next(m.port_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_connectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb_msgs::srv_connectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb_msgs::srv_connectResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_connected);
    s << indent << "port_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.port_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_CONNECTRESPONSE_H
