// Generated by gencpp from file tb_msgs/srv_connect_portsResponse.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_CONNECT_PORTSRESPONSE_H
#define TB_MSGS_MESSAGE_SRV_CONNECT_PORTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb_msgs
{
template <class ContainerAllocator>
struct srv_connect_portsResponse_
{
  typedef srv_connect_portsResponse_<ContainerAllocator> Type;

  srv_connect_portsResponse_()
    : connect_ports()  {
    }
  srv_connect_portsResponse_(const ContainerAllocator& _alloc)
    : connect_ports(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _connect_ports_type;
  _connect_ports_type connect_ports;





  typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_connect_portsResponse_

typedef ::tb_msgs::srv_connect_portsResponse_<std::allocator<void> > srv_connect_portsResponse;

typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsResponse > srv_connect_portsResponsePtr;
typedef boost::shared_ptr< ::tb_msgs::srv_connect_portsResponse const> srv_connect_portsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.connect_ports == rhs.connect_ports;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4597851d4809b09efcd00c999ac73b7b";
  }

  static const char* value(const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4597851d4809b09eULL;
  static const uint64_t static_value2 = 0xfcd00c999ac73b7bULL;
};

template<class ContainerAllocator>
struct DataType< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb_msgs/srv_connect_portsResponse";
  }

  static const char* value(const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] connect_ports\n"
"\n"
;
  }

  static const char* value(const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connect_ports);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_connect_portsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb_msgs::srv_connect_portsResponse_<ContainerAllocator>& v)
  {
    s << indent << "connect_ports[]" << std::endl;
    for (size_t i = 0; i < v.connect_ports.size(); ++i)
    {
      s << indent << "  connect_ports[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.connect_ports[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_CONNECT_PORTSRESPONSE_H
