// Generated by gencpp from file tb_msgs/srv_debug_pid_stream.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_DEBUG_PID_STREAM_H
#define TB_MSGS_MESSAGE_SRV_DEBUG_PID_STREAM_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_debug_pid_streamRequest.h>
#include <tb_msgs/srv_debug_pid_streamResponse.h>


namespace tb_msgs
{

struct srv_debug_pid_stream
{

typedef srv_debug_pid_streamRequest Request;
typedef srv_debug_pid_streamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_debug_pid_stream
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_debug_pid_stream > {
  static const char* value()
  {
    return "9f6f8728cdcf6a5f6fc593762c9a25b3";
  }

  static const char* value(const ::tb_msgs::srv_debug_pid_stream&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_debug_pid_stream > {
  static const char* value()
  {
    return "tb_msgs/srv_debug_pid_stream";
  }

  static const char* value(const ::tb_msgs::srv_debug_pid_stream&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_debug_pid_streamRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_debug_pid_stream >
template<>
struct MD5Sum< ::tb_msgs::srv_debug_pid_streamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_debug_pid_stream >::value();
  }
  static const char* value(const ::tb_msgs::srv_debug_pid_streamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_debug_pid_streamRequest> should match
// service_traits::DataType< ::tb_msgs::srv_debug_pid_stream >
template<>
struct DataType< ::tb_msgs::srv_debug_pid_streamRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_debug_pid_stream >::value();
  }
  static const char* value(const ::tb_msgs::srv_debug_pid_streamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_debug_pid_streamResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_debug_pid_stream >
template<>
struct MD5Sum< ::tb_msgs::srv_debug_pid_streamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_debug_pid_stream >::value();
  }
  static const char* value(const ::tb_msgs::srv_debug_pid_streamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_debug_pid_streamResponse> should match
// service_traits::DataType< ::tb_msgs::srv_debug_pid_stream >
template<>
struct DataType< ::tb_msgs::srv_debug_pid_streamResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_debug_pid_stream >::value();
  }
  static const char* value(const ::tb_msgs::srv_debug_pid_streamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_DEBUG_PID_STREAM_H
