// Generated by gencpp from file tb_msgs/srv_reset_servo_idResponse.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_RESET_SERVO_IDRESPONSE_H
#define TB_MSGS_MESSAGE_SRV_RESET_SERVO_IDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb_msgs
{
template <class ContainerAllocator>
struct srv_reset_servo_idResponse_
{
  typedef srv_reset_servo_idResponse_<ContainerAllocator> Type;

  srv_reset_servo_idResponse_()
    : target_sid(0)  {
    }
  srv_reset_servo_idResponse_(const ContainerAllocator& _alloc)
    : target_sid(0)  {
  (void)_alloc;
    }



   typedef uint8_t _target_sid_type;
  _target_sid_type target_sid;





  typedef boost::shared_ptr< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_reset_servo_idResponse_

typedef ::tb_msgs::srv_reset_servo_idResponse_<std::allocator<void> > srv_reset_servo_idResponse;

typedef boost::shared_ptr< ::tb_msgs::srv_reset_servo_idResponse > srv_reset_servo_idResponsePtr;
typedef boost::shared_ptr< ::tb_msgs::srv_reset_servo_idResponse const> srv_reset_servo_idResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target_sid == rhs.target_sid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator1> & lhs, const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32afbd61d20d82af1274d91a8810fc0b";
  }

  static const char* value(const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32afbd61d20d82afULL;
  static const uint64_t static_value2 = 0x1274d91a8810fc0bULL;
};

template<class ContainerAllocator>
struct DataType< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb_msgs/srv_reset_servo_idResponse";
  }

  static const char* value(const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 target_sid\n"
"\n"
;
  }

  static const char* value(const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_sid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_reset_servo_idResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb_msgs::srv_reset_servo_idResponse_<ContainerAllocator>& v)
  {
    s << indent << "target_sid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_sid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_RESET_SERVO_IDRESPONSE_H
