// Generated by gencpp from file tb_msgs/srv_get_tbcore_statusRequest.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_GET_TBCORE_STATUSREQUEST_H
#define TB_MSGS_MESSAGE_SRV_GET_TBCORE_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb_msgs
{
template <class ContainerAllocator>
struct srv_get_tbcore_statusRequest_
{
  typedef srv_get_tbcore_statusRequest_<ContainerAllocator> Type;

  srv_get_tbcore_statusRequest_()
    {
    }
  srv_get_tbcore_statusRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srv_get_tbcore_statusRequest_

typedef ::tb_msgs::srv_get_tbcore_statusRequest_<std::allocator<void> > srv_get_tbcore_statusRequest;

typedef boost::shared_ptr< ::tb_msgs::srv_get_tbcore_statusRequest > srv_get_tbcore_statusRequestPtr;
typedef boost::shared_ptr< ::tb_msgs::srv_get_tbcore_statusRequest const> srv_get_tbcore_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb_msgs/srv_get_tbcore_statusRequest";
  }

  static const char* value(const ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#goal request definition\n"
;
  }

  static const char* value(const ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_get_tbcore_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tb_msgs::srv_get_tbcore_statusRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_GET_TBCORE_STATUSREQUEST_H
