// Generated by gencpp from file tb_msgs/srv_get_servo_info.msg
// DO NOT EDIT!


#ifndef TB_MSGS_MESSAGE_SRV_GET_SERVO_INFO_H
#define TB_MSGS_MESSAGE_SRV_GET_SERVO_INFO_H

#include <ros/service_traits.h>


#include <tb_msgs/srv_get_servo_infoRequest.h>
#include <tb_msgs/srv_get_servo_infoResponse.h>


namespace tb_msgs
{

struct srv_get_servo_info
{

typedef srv_get_servo_infoRequest Request;
typedef srv_get_servo_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_get_servo_info
} // namespace tb_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tb_msgs::srv_get_servo_info > {
  static const char* value()
  {
    return "cf742bfc72c6e98136ccd18780df03f9";
  }

  static const char* value(const ::tb_msgs::srv_get_servo_info&) { return value(); }
};

template<>
struct DataType< ::tb_msgs::srv_get_servo_info > {
  static const char* value()
  {
    return "tb_msgs/srv_get_servo_info";
  }

  static const char* value(const ::tb_msgs::srv_get_servo_info&) { return value(); }
};


// service_traits::MD5Sum< ::tb_msgs::srv_get_servo_infoRequest> should match
// service_traits::MD5Sum< ::tb_msgs::srv_get_servo_info >
template<>
struct MD5Sum< ::tb_msgs::srv_get_servo_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_get_servo_info >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_servo_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_get_servo_infoRequest> should match
// service_traits::DataType< ::tb_msgs::srv_get_servo_info >
template<>
struct DataType< ::tb_msgs::srv_get_servo_infoRequest>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_get_servo_info >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_servo_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tb_msgs::srv_get_servo_infoResponse> should match
// service_traits::MD5Sum< ::tb_msgs::srv_get_servo_info >
template<>
struct MD5Sum< ::tb_msgs::srv_get_servo_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tb_msgs::srv_get_servo_info >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_servo_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tb_msgs::srv_get_servo_infoResponse> should match
// service_traits::DataType< ::tb_msgs::srv_get_servo_info >
template<>
struct DataType< ::tb_msgs::srv_get_servo_infoResponse>
{
  static const char* value()
  {
    return DataType< ::tb_msgs::srv_get_servo_info >::value();
  }
  static const char* value(const ::tb_msgs::srv_get_servo_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TB_MSGS_MESSAGE_SRV_GET_SERVO_INFO_H
