# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tb_msgs/srv_servo_write_eepRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class srv_servo_write_eepRequest(genpy.Message):
  _md5sum = "8aaa44910eba83c9c77a09649fd2c5c3"
  _type = "tb_msgs/srv_servo_write_eepRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8   sid
uint8   address
#the memory at this address could be 2 bytes or 1 byte
bool    is_2bytes_address
uint16  value
"""
  __slots__ = ['sid','address','is_2bytes_address','value']
  _slot_types = ['uint8','uint8','bool','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sid,address,is_2bytes_address,value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(srv_servo_write_eepRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sid is None:
        self.sid = 0
      if self.address is None:
        self.address = 0
      if self.is_2bytes_address is None:
        self.is_2bytes_address = False
      if self.value is None:
        self.value = 0
    else:
      self.sid = 0
      self.address = 0
      self.is_2bytes_address = False
      self.value = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3BH().pack(_x.sid, _x.address, _x.is_2bytes_address, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sid, _x.address, _x.is_2bytes_address, _x.value,) = _get_struct_3BH().unpack(str[start:end])
      self.is_2bytes_address = bool(self.is_2bytes_address)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3BH().pack(_x.sid, _x.address, _x.is_2bytes_address, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sid, _x.address, _x.is_2bytes_address, _x.value,) = _get_struct_3BH().unpack(str[start:end])
      self.is_2bytes_address = bool(self.is_2bytes_address)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3BH = None
def _get_struct_3BH():
    global _struct_3BH
    if _struct_3BH is None:
        _struct_3BH = struct.Struct("<3BH")
    return _struct_3BH
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tb_msgs/srv_servo_write_eepResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class srv_servo_write_eepResponse(genpy.Message):
  _md5sum = "f7aab4d9f19f7964e5184e72901032e3"
  _type = "tb_msgs/srv_servo_write_eepResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 sid

"""
  __slots__ = ['sid']
  _slot_types = ['uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(srv_servo_write_eepResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sid is None:
        self.sid = 0
    else:
      self.sid = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.sid
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.sid,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.sid
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.sid,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class srv_servo_write_eep(object):
  _type          = 'tb_msgs/srv_servo_write_eep'
  _md5sum = 'c3b79ffab4f13eedb654bb8d07216bc2'
  _request_class  = srv_servo_write_eepRequest
  _response_class = srv_servo_write_eepResponse
