// Generated by gencpp from file people_face_identification/DetectFaceFromImg.msg
// DO NOT EDIT!


#ifndef PEOPLE_FACE_IDENTIFICATION_MESSAGE_DETECTFACEFROMIMG_H
#define PEOPLE_FACE_IDENTIFICATION_MESSAGE_DETECTFACEFROMIMG_H

#include <ros/service_traits.h>


#include <people_face_identification/DetectFaceFromImgRequest.h>
#include <people_face_identification/DetectFaceFromImgResponse.h>


namespace people_face_identification
{

struct DetectFaceFromImg
{

typedef DetectFaceFromImgRequest Request;
typedef DetectFaceFromImgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectFaceFromImg
} // namespace people_face_identification


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::people_face_identification::DetectFaceFromImg > {
  static const char* value()
  {
    return "880eeace0c9edca39ffaf298047fafc9";
  }

  static const char* value(const ::people_face_identification::DetectFaceFromImg&) { return value(); }
};

template<>
struct DataType< ::people_face_identification::DetectFaceFromImg > {
  static const char* value()
  {
    return "people_face_identification/DetectFaceFromImg";
  }

  static const char* value(const ::people_face_identification::DetectFaceFromImg&) { return value(); }
};


// service_traits::MD5Sum< ::people_face_identification::DetectFaceFromImgRequest> should match
// service_traits::MD5Sum< ::people_face_identification::DetectFaceFromImg >
template<>
struct MD5Sum< ::people_face_identification::DetectFaceFromImgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::people_face_identification::DetectFaceFromImg >::value();
  }
  static const char* value(const ::people_face_identification::DetectFaceFromImgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::people_face_identification::DetectFaceFromImgRequest> should match
// service_traits::DataType< ::people_face_identification::DetectFaceFromImg >
template<>
struct DataType< ::people_face_identification::DetectFaceFromImgRequest>
{
  static const char* value()
  {
    return DataType< ::people_face_identification::DetectFaceFromImg >::value();
  }
  static const char* value(const ::people_face_identification::DetectFaceFromImgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::people_face_identification::DetectFaceFromImgResponse> should match
// service_traits::MD5Sum< ::people_face_identification::DetectFaceFromImg >
template<>
struct MD5Sum< ::people_face_identification::DetectFaceFromImgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::people_face_identification::DetectFaceFromImg >::value();
  }
  static const char* value(const ::people_face_identification::DetectFaceFromImgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::people_face_identification::DetectFaceFromImgResponse> should match
// service_traits::DataType< ::people_face_identification::DetectFaceFromImg >
template<>
struct DataType< ::people_face_identification::DetectFaceFromImgResponse>
{
  static const char* value()
  {
    return DataType< ::people_face_identification::DetectFaceFromImg >::value();
  }
  static const char* value(const ::people_face_identification::DetectFaceFromImgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEOPLE_FACE_IDENTIFICATION_MESSAGE_DETECTFACEFROMIMG_H
