// Generated by gencpp from file people_face_identification/DetectFaceFromImgResponse.msg
// DO NOT EDIT!


#ifndef PEOPLE_FACE_IDENTIFICATION_MESSAGE_DETECTFACEFROMIMGRESPONSE_H
#define PEOPLE_FACE_IDENTIFICATION_MESSAGE_DETECTFACEFROMIMGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robocup_msgs/Entity2DList.h>

namespace people_face_identification
{
template <class ContainerAllocator>
struct DetectFaceFromImgResponse_
{
  typedef DetectFaceFromImgResponse_<ContainerAllocator> Type;

  DetectFaceFromImgResponse_()
    : entityList()  {
    }
  DetectFaceFromImgResponse_(const ContainerAllocator& _alloc)
    : entityList(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robocup_msgs::Entity2DList_<ContainerAllocator>  _entityList_type;
  _entityList_type entityList;





  typedef boost::shared_ptr< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectFaceFromImgResponse_

typedef ::people_face_identification::DetectFaceFromImgResponse_<std::allocator<void> > DetectFaceFromImgResponse;

typedef boost::shared_ptr< ::people_face_identification::DetectFaceFromImgResponse > DetectFaceFromImgResponsePtr;
typedef boost::shared_ptr< ::people_face_identification::DetectFaceFromImgResponse const> DetectFaceFromImgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator1> & lhs, const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.entityList == rhs.entityList;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator1> & lhs, const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace people_face_identification

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9825ff008a097988dc078fe818a51870";
  }

  static const char* value(const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9825ff008a097988ULL;
  static const uint64_t static_value2 = 0xdc078fe818a51870ULL;
};

template<class ContainerAllocator>
struct DataType< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "people_face_identification/DetectFaceFromImgResponse";
  }

  static const char* value(const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robocup_msgs/Entity2DList entityList\n"
"\n"
"================================================================================\n"
"MSG: robocup_msgs/Entity2DList\n"
"std_msgs/Header header\n"
"Entity2D[] entity2DList\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robocup_msgs/Entity2D\n"
"std_msgs/Header header\n"
"geometry_msgs/Pose2D pose\n"
"string label\n"
"Box bounding_box\n"
"float32 score\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: robocup_msgs/Box\n"
"int32 x\n"
"int32 y\n"
"int32 width\n"
"int32 height\n"
;
  }

  static const char* value(const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.entityList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectFaceFromImgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::people_face_identification::DetectFaceFromImgResponse_<ContainerAllocator>& v)
  {
    s << indent << "entityList: ";
    s << std::endl;
    Printer< ::robocup_msgs::Entity2DList_<ContainerAllocator> >::stream(s, indent + "  ", v.entityList);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEOPLE_FACE_IDENTIFICATION_MESSAGE_DETECTFACEFROMIMGRESPONSE_H
