// Generated by gencpp from file people_face_identification/LearnFaceRequest.msg
// DO NOT EDIT!


#ifndef PEOPLE_FACE_IDENTIFICATION_MESSAGE_LEARNFACEREQUEST_H
#define PEOPLE_FACE_IDENTIFICATION_MESSAGE_LEARNFACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace people_face_identification
{
template <class ContainerAllocator>
struct LearnFaceRequest_
{
  typedef LearnFaceRequest_<ContainerAllocator> Type;

  LearnFaceRequest_()
    : label()  {
    }
  LearnFaceRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LearnFaceRequest_

typedef ::people_face_identification::LearnFaceRequest_<std::allocator<void> > LearnFaceRequest;

typedef boost::shared_ptr< ::people_face_identification::LearnFaceRequest > LearnFaceRequestPtr;
typedef boost::shared_ptr< ::people_face_identification::LearnFaceRequest const> LearnFaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::people_face_identification::LearnFaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::people_face_identification::LearnFaceRequest_<ContainerAllocator1> & lhs, const ::people_face_identification::LearnFaceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::people_face_identification::LearnFaceRequest_<ContainerAllocator1> & lhs, const ::people_face_identification::LearnFaceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace people_face_identification

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea23f97416b04c6151d2b576c0665ac1";
  }

  static const char* value(const ::people_face_identification::LearnFaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea23f97416b04c61ULL;
  static const uint64_t static_value2 = 0x51d2b576c0665ac1ULL;
};

template<class ContainerAllocator>
struct DataType< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "people_face_identification/LearnFaceRequest";
  }

  static const char* value(const ::people_face_identification::LearnFaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
;
  }

  static const char* value(const ::people_face_identification::LearnFaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearnFaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::people_face_identification::LearnFaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::people_face_identification::LearnFaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEOPLE_FACE_IDENTIFICATION_MESSAGE_LEARNFACEREQUEST_H
