// Generated by gencpp from file people_face_identification/LearnFaceFromImgRequest.msg
// DO NOT EDIT!


#ifndef PEOPLE_FACE_IDENTIFICATION_MESSAGE_LEARNFACEFROMIMGREQUEST_H
#define PEOPLE_FACE_IDENTIFICATION_MESSAGE_LEARNFACEFROMIMGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace people_face_identification
{
template <class ContainerAllocator>
struct LearnFaceFromImgRequest_
{
  typedef LearnFaceFromImgRequest_<ContainerAllocator> Type;

  LearnFaceFromImgRequest_()
    : label()
    , img()  {
    }
  LearnFaceFromImgRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , img(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;





  typedef boost::shared_ptr< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LearnFaceFromImgRequest_

typedef ::people_face_identification::LearnFaceFromImgRequest_<std::allocator<void> > LearnFaceFromImgRequest;

typedef boost::shared_ptr< ::people_face_identification::LearnFaceFromImgRequest > LearnFaceFromImgRequestPtr;
typedef boost::shared_ptr< ::people_face_identification::LearnFaceFromImgRequest const> LearnFaceFromImgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator1> & lhs, const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.img == rhs.img;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator1> & lhs, const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace people_face_identification

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eb9871b8b2787493810270c036cb11e";
  }

  static const char* value(const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eb9871b8b278749ULL;
  static const uint64_t static_value2 = 0x3810270c036cb11eULL;
};

template<class ContainerAllocator>
struct DataType< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "people_face_identification/LearnFaceFromImgRequest";
  }

  static const char* value(const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"sensor_msgs/Image img\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearnFaceFromImgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::people_face_identification::LearnFaceFromImgRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEOPLE_FACE_IDENTIFICATION_MESSAGE_LEARNFACEFROMIMGREQUEST_H
