// Generated by gencpp from file people_face_identification/ToogleFaceDetection.msg
// DO NOT EDIT!


#ifndef PEOPLE_FACE_IDENTIFICATION_MESSAGE_TOOGLEFACEDETECTION_H
#define PEOPLE_FACE_IDENTIFICATION_MESSAGE_TOOGLEFACEDETECTION_H

#include <ros/service_traits.h>


#include <people_face_identification/ToogleFaceDetectionRequest.h>
#include <people_face_identification/ToogleFaceDetectionResponse.h>


namespace people_face_identification
{

struct ToogleFaceDetection
{

typedef ToogleFaceDetectionRequest Request;
typedef ToogleFaceDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToogleFaceDetection
} // namespace people_face_identification


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::people_face_identification::ToogleFaceDetection > {
  static const char* value()
  {
    return "38b844019f9cd05d08db5ac79f1c1789";
  }

  static const char* value(const ::people_face_identification::ToogleFaceDetection&) { return value(); }
};

template<>
struct DataType< ::people_face_identification::ToogleFaceDetection > {
  static const char* value()
  {
    return "people_face_identification/ToogleFaceDetection";
  }

  static const char* value(const ::people_face_identification::ToogleFaceDetection&) { return value(); }
};


// service_traits::MD5Sum< ::people_face_identification::ToogleFaceDetectionRequest> should match
// service_traits::MD5Sum< ::people_face_identification::ToogleFaceDetection >
template<>
struct MD5Sum< ::people_face_identification::ToogleFaceDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::people_face_identification::ToogleFaceDetection >::value();
  }
  static const char* value(const ::people_face_identification::ToogleFaceDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::people_face_identification::ToogleFaceDetectionRequest> should match
// service_traits::DataType< ::people_face_identification::ToogleFaceDetection >
template<>
struct DataType< ::people_face_identification::ToogleFaceDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::people_face_identification::ToogleFaceDetection >::value();
  }
  static const char* value(const ::people_face_identification::ToogleFaceDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::people_face_identification::ToogleFaceDetectionResponse> should match
// service_traits::MD5Sum< ::people_face_identification::ToogleFaceDetection >
template<>
struct MD5Sum< ::people_face_identification::ToogleFaceDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::people_face_identification::ToogleFaceDetection >::value();
  }
  static const char* value(const ::people_face_identification::ToogleFaceDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::people_face_identification::ToogleFaceDetectionResponse> should match
// service_traits::DataType< ::people_face_identification::ToogleFaceDetection >
template<>
struct DataType< ::people_face_identification::ToogleFaceDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::people_face_identification::ToogleFaceDetection >::value();
  }
  static const char* value(const ::people_face_identification::ToogleFaceDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEOPLE_FACE_IDENTIFICATION_MESSAGE_TOOGLEFACEDETECTION_H
