# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tb_msgs/cmd_motor_pwm.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class cmd_motor_pwm(genpy.Message):
  _md5sum = "94dfec4e869196e493f45bf1370261b6"
  _type = "tb_msgs/cmd_motor_pwm"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
#Set PWM value for each motor from -1000 to 1000
# motor_i_enable:
#   true: set PWM = motor_i value
#   false: set PWM = 0
bool motor_1_enable
float64 pwm_motor_1
uint16 baseoffset_1

bool motor_2_enable
float64 pwm_motor_2
uint16 baseoffset_2

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','motor_1_enable','pwm_motor_1','baseoffset_1','motor_2_enable','pwm_motor_2','baseoffset_2']
  _slot_types = ['std_msgs/Header','bool','float64','uint16','bool','float64','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,motor_1_enable,pwm_motor_1,baseoffset_1,motor_2_enable,pwm_motor_2,baseoffset_2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cmd_motor_pwm, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.motor_1_enable is None:
        self.motor_1_enable = False
      if self.pwm_motor_1 is None:
        self.pwm_motor_1 = 0.
      if self.baseoffset_1 is None:
        self.baseoffset_1 = 0
      if self.motor_2_enable is None:
        self.motor_2_enable = False
      if self.pwm_motor_2 is None:
        self.pwm_motor_2 = 0.
      if self.baseoffset_2 is None:
        self.baseoffset_2 = 0
    else:
      self.header = std_msgs.msg.Header()
      self.motor_1_enable = False
      self.pwm_motor_1 = 0.
      self.baseoffset_1 = 0
      self.motor_2_enable = False
      self.pwm_motor_2 = 0.
      self.baseoffset_2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BdHBdH().pack(_x.motor_1_enable, _x.pwm_motor_1, _x.baseoffset_1, _x.motor_2_enable, _x.pwm_motor_2, _x.baseoffset_2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 22
      (_x.motor_1_enable, _x.pwm_motor_1, _x.baseoffset_1, _x.motor_2_enable, _x.pwm_motor_2, _x.baseoffset_2,) = _get_struct_BdHBdH().unpack(str[start:end])
      self.motor_1_enable = bool(self.motor_1_enable)
      self.motor_2_enable = bool(self.motor_2_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BdHBdH().pack(_x.motor_1_enable, _x.pwm_motor_1, _x.baseoffset_1, _x.motor_2_enable, _x.pwm_motor_2, _x.baseoffset_2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 22
      (_x.motor_1_enable, _x.pwm_motor_1, _x.baseoffset_1, _x.motor_2_enable, _x.pwm_motor_2, _x.baseoffset_2,) = _get_struct_BdHBdH().unpack(str[start:end])
      self.motor_1_enable = bool(self.motor_1_enable)
      self.motor_2_enable = bool(self.motor_2_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_BdHBdH = None
def _get_struct_BdHBdH():
    global _struct_BdHBdH
    if _struct_BdHBdH is None:
        _struct_BdHBdH = struct.Struct("<BdHBdH")
    return _struct_BdHBdH
